server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/metrotunr
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: "NGU4MjcxNzQtMzNiMi00NjI0LWFhZTQtM2MyYTM3OTQ1NTQz"
  expiration: 86400000